schutzbot/deploy: use the full db container name
With the update to RHEL 10, running a container using its shortname
tries to prompt for resolving the full name and fails with:

  Error: short-name resolution enforced but cannot prompt without a TTY